# Generated by Django 3.1.1 on 2020-09-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='mail',
            new_name='user_mail',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='user_name',
        ),
    ]
